Repository nbc-react-3rd-nextjs-project-a9/Where2Go, pull requests merged in 2023-12, with the labels that each got.

#4 [feat/home] update : header Nav 생성
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: 🎉add, 💄 style, ✨ update

#6 [feat/home] (#2) 중간 pull request
  package.json
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Carousel.tsx
  src/components/PostCardList.tsx
  src/components/filterTag/FilterTag.tsx
  src/components/filterTag/FilterTagList.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/layout/Section.tsx
  src/data/mockPlace.ts
  src/types/enum.ts
  yarn.lock
Labels: 🎉add

#8 [Feat/map] 지도 컴포넌트 추가 (#3)
  package.json
  src/app/map/MapContainer.tsx
  src/app/map/SearchMap.tsx
  src/app/map/page.tsx
  tsconfig.json
  yarn.lock
Labels: 🎉add

#9 refact : filterTagList 리팩토링 (#2)
  src/app/page.tsx
  src/components/filterTag/FilterTag.tsx
  src/components/filterTag/FilterTagList.tsx
  src/data/tagData.ts
  src/hooks/index.tsx
  src/hooks/useTag.tsx
Labels: ♻️ refactor

#13 add: not-found 페이지 추가 (#3)
  src/app/form/page.tsx
  src/app/layout.tsx
  src/app/map/PlacesSearch.tsx
  src/app/map/SearchMap.tsx
  src/app/map/page.tsx
  src/app/not-found.tsx
Labels: 🎉add, 🐛 bugfix

#30 [Feat/home] SSR 방식으로 변환
  src/app/HomeFilterTagList.tsx
  src/app/api/places/route.ts
  src/app/page.tsx
  src/components/PostCardList.tsx
  src/components/filterTag/FilterTagList.tsx
Labels: 🎉add, 🐛 bugfix, ♻️ refactor, 💄 style, ✨ update
